[package]
name = "pycaputo"
version = "2023.3.0"
edition = "2021"
license = "LICENCES/MIT.txt"

[lib]
name = "pycaputo"
crate-type = ["cdylib"]

[dependencies]
rand = "*"

[dependencies.pyo3]
version = "0.18.1"
features = ["abi3-py38"]
